export const PROFESSIONAL_PROFILE_MOCK = {
  usuario: {
    nombre: "Alejandro",
    apellido: "Castro",
    titulo: "Full Stack Developer · Especialista en arquitecturas web escalables",
    ubicacion: "Cochabamba, Bolivia",
    disponible: true,
    biografia:
      "Desarrollador Full Stack con 6 años de experiencia construyendo aplicaciones web robustas y escalables. Apasionado por el diseño de sistemas, las buenas prácticas de código y la experiencia de usuario. Actualmente enfocado en arquitecturas con microservicios y DevOps.",
    stats: { proyectos: 12, experiencia: 6, empleadores: 4, visitas: 148 },
    url: "stackfolio.io/alejandro",
  },
  social: [
    { platform: "github", label: "github.com/alejcastro", url: "https://github.com/alejcastro" },
    { platform: "linkedin", label: "linkedin.com/in/alejcastro", url: "https://linkedin.com/in/alejcastro" },
    { platform: "web", label: "alejandro.dev", url: "https://alejandro.dev" },
    { platform: "twitter", label: "@alejcastro_dev", url: "https://x.com/alejcastro_dev" },
  ],
  habilidades: [
    {
      grupo: "Frontend",
      tags: [
        { label: "React", expert: true },
        { label: "TypeScript", expert: true },
        { label: "Vue.js", expert: false },
        { label: "Tailwind", expert: false },
      ],
    },
    {
      grupo: "Backend",
      tags: [
        { label: "Node.js", expert: true },
        { label: "PHP", expert: true },
        { label: "Java Spring", expert: false },
        { label: "REST API", expert: false },
      ],
    },
    {
      grupo: "Base de datos",
      tags: [
        { label: "PostgreSQL", expert: true },
        { label: "MySQL", expert: false },
        { label: "Redis", expert: false },
      ],
    },
    {
      grupo: "DevOps y herramientas",
      tags: [
        { label: "Docker", expert: false },
        { label: "Git", expert: false },
        { label: "Linux", expert: false },
        { label: "CI/CD", expert: false },
      ],
    },
  ],
  proyectos: [
    {
      id: "mock-marketflow",
      emoji: "🛒",
      badge: "LIVE",
      bg: "linear-gradient(135deg,#2D3142,#4F5D75)",
      titulo: "MarketFlow - E-commerce Platform",
      desc: "Plataforma de comercio electrónico con inventario en tiempo real, pasarela de pagos y panel de analíticas.",
      tags: ["React", "Node.js", "PostgreSQL", "Docker"],
      demo: true,
      fecha: "Mar 2024",
      url_demo: "#",
      url_repositorio: "#",
    },
    {
      id: "mock-datapulse",
      emoji: "📊",
      badge: "LIVE",
      bg: "linear-gradient(135deg,#3a2a1e,#7a4a2a)",
      titulo: "DataPulse - Dashboard Analytics",
      desc: "Dashboard interactivo para visualización de métricas de negocio con reportes exportables y alertas configurables.",
      tags: ["Vue.js", "PHP", "MySQL", "Chart.js"],
      demo: true,
      fecha: "Oct 2023",
      url_demo: "#",
      url_repositorio: "#",
    },
    {
      id: "mock-medtrack",
      emoji: "🏥",
      badge: "WIP",
      bg: "linear-gradient(135deg,#1a2a3a,#2D3142)",
      titulo: "MedTrack - Sistema Clínico",
      desc: "Sistema de gestión de pacientes, citas e historial médico para clínicas privadas.",
      tags: ["Java Spring", "React", "PostgreSQL", "Tomcat"],
      demo: false,
      fecha: "En progreso",
      url_demo: "#",
      url_repositorio: "#",
    },
  ],
  experiencia: [
    {
      id: "mock-exp-1",
      icon: "🚀",
      rol: "Senior Full Stack Developer",
      actual: true,
      fecha: "Ene 2023 - Presente",
      empresa: "TechNova Bolivia · Tiempo completo",
      desc: "Liderazgo técnico del equipo de producto. Diseño de arquitectura, revisión de código y mentoring de desarrolladores junior.",
    },
    {
      id: "mock-exp-2",
      icon: "💡",
      rol: "Full Stack Developer",
      actual: false,
      fecha: "Mar 2020 - Dic 2022",
      empresa: "Soluciones Digitales LATAM · Tiempo completo",
      desc: "Desarrollo de aplicaciones web, integraciones de APIs y optimización de bases de datos.",
    },
  ],
  formacion: [
    {
      id: "mock-form-1",
      titulo: "Ing. de Sistemas",
      inst: "Universidad Mayor de San Simón",
      period: "2015 - 2020",
    },
    {
      id: "mock-form-2",
      titulo: "Cert. Cloud Architecture",
      inst: "AWS / Coursera",
      period: "2022",
    },
  ],
};
