export const cvUi = {
  root: { display: "grid", gap: 24 },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  headerLeft: { display: "grid", gap: 4 },
  title: {
    fontFamily: "var(--f-title)",
    fontWeight: 800,
    fontSize: "1.15rem",
    color: "var(--text)",
  },
  subtitle: {
    fontFamily: "var(--f-body)",
    fontSize: "0.82rem",
    color: "var(--muted)",
  },
  actions: { display: "flex", gap: 8, flexWrap: "wrap" },
  btnPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 16px",
    borderRadius: 10,
    border: "none",
    background: "linear-gradient(135deg, #12369e 0%, #255dde 100%)",
    color: "#fff",
    fontFamily: "var(--f-ui)",
    fontSize: "0.83rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(37,93,222,.25)",
  },
  btnSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 16px",
    borderRadius: 10,
    border: "1px solid var(--cv-cancel-btn-border)",
    background: "var(--cv-cancel-btn-bg)",
    color: "var(--text)",
    fontFamily: "var(--f-ui)",
    fontSize: "0.83rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  strip: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 12,
    background: "var(--cv-strip-bg)",
    border: "1px solid var(--cv-strip-border)",
    fontFamily: "var(--f-body)",
    fontSize: "0.78rem",
    color: "var(--cv-strip-text)",
  },
  errorBox: {
    padding: "10px 14px",
    borderRadius: 10,
    background: "var(--cv-error-bg)",
    border: "1px solid var(--cv-error-border)",
    color: "var(--cv-error-text)",
    fontFamily: "var(--f-body)",
    fontSize: "0.82rem",
  },
  loadingBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "48px 24px",
    color: "var(--cv-loading-color)",
    fontFamily: "var(--f-body)",
    fontSize: "0.85rem",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    padding: "48px 24px",
    borderRadius: 16,
    background: "var(--cv-empty-bg)",
    border: "1.5px dashed var(--cv-empty-border)",
    textAlign: "center",
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background:
      "linear-gradient(135deg, rgba(37,93,222,.08) 0%, rgba(37,93,222,.14) 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#255dde",
  },
  emptyTitle: {
    fontFamily: "var(--f-title)",
    fontWeight: 700,
    fontSize: "1rem",
    color: "var(--text)",
  },
  emptyText: {
    fontFamily: "var(--f-body)",
    fontSize: "0.82rem",
    color: "var(--muted)",
    maxWidth: 320,
    lineHeight: 1.6,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
    gap: 16,
  },
  card: {
    borderRadius: 16,
    background: "var(--cv-card-bg)",
    border: "1px solid var(--cv-card-border)",
    boxShadow: "var(--cv-card-shadow)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  cardPreview: (template) => ({
    height: 120,
    background:
      template === "navy"
        ? "linear-gradient(135deg, #0E2A5C 0%, #185FA5 100%)"
        : template === "forest"
          ? "linear-gradient(135deg, #14532d 0%, #16a34a 100%)"
          : template === "crimson"
            ? "linear-gradient(135deg, #7f1d1d 0%, #dc2626 100%)"
            : template === "bicolor"
              ? "linear-gradient(135deg, #1e293b 0%, #38bdf8 100%)"
              : template === "tech"
                ? "linear-gradient(135deg, #0d1117 0%, #58a6ff 100%)"
                : template === "minimal"
                  ? "linear-gradient(135deg, #e2e8f0 0%, #94a3b8 100%)"
                  : "linear-gradient(135deg, #1e293b 0%, #0d9488 100%)",
    position: "relative",
    overflow: "hidden",
  }),
  cardPreviewLines: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "16px 20px",
    gap: 6,
  },
  previewLine: (w, op = 0.3) => ({
    height: 6,
    borderRadius: 3,
    background: `rgba(255,255,255,${op})`,
    width: w,
  }),
  cardBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 999,
    background: "rgba(255,255,255,.18)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,.25)",
    color: "#fff",
    fontFamily: "var(--f-ui)",
    fontSize: "0.68rem",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  cardBody: {
    padding: "14px 16px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    background: "var(--cv-card-bg)",
  },
  cardName: {
    fontFamily: "var(--f-title)",
    fontWeight: 700,
    fontSize: "0.95rem",
    color: "var(--text)",
  },
  cardDesc: {
    fontFamily: "var(--f-body)",
    fontSize: "0.78rem",
    color: "var(--muted)",
    lineHeight: 1.5,
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "var(--f-ui)",
    fontSize: "0.72rem",
    color: "var(--muted)",
    marginTop: "auto",
  },
  cardFooter: {
    padding: "10px 16px",
    borderTop: "1px solid var(--cv-card-footer)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    background: "var(--cv-card-bg)",
  },
  visibleBadge: (v) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 999,
    fontFamily: "var(--f-ui)",
    fontSize: "0.7rem",
    fontWeight: 700,
    background: v ? "rgba(13,148,136,.08)" : "rgba(107,114,128,.08)",
    color: v ? "#0d9488" : "#6b7280",
    border: `1px solid ${v ? "rgba(13,148,136,.18)" : "rgba(107,114,128,.18)"}`,
  }),
  iconGroup: { display: "flex", gap: 4 },
  iconBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    border: "1px solid var(--cv-icon-btn-border)",
    background: "var(--cv-icon-btn-bg)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "var(--muted)",
  },
};
