import { dashboardShell } from "../../../styles/components/dashboardShell";

export const profileUi = {
  shell: { ...dashboardShell.surfaceCard, borderRadius: 24 },
  hero: { overflow: "hidden" },
  cover: {
    minHeight: 168,
    background: "linear-gradient(135deg, #0d1f3c 0%, #1e3a5f 62%, #7fc6f3 100%)",
    position: "relative",
  },
  section: { ...dashboardShell.surfaceCard, borderRadius: 22, padding: 18 },
  title: { fontFamily: "var(--f-title)", fontSize: "1rem", fontWeight: 800, color: "var(--text)" },
  body: { fontFamily: "var(--f-body)", fontSize: ".92rem", lineHeight: 1.7, color: "var(--body)" },
  muted: { fontFamily: "var(--f-ui)", fontSize: ".82rem", color: "var(--muted)" },
  input: { width: "100%", minHeight: 46, borderRadius: 14, border: "1px solid rgba(205,225,245,.78)", background: "#fff", padding: "0 14px", color: "var(--text)", fontFamily: "var(--f-ui)", fontSize: ".92rem", outline: "none", boxShadow: "0 1px 0 rgba(255,255,255,.7) inset" },
  textarea: { width: "100%", minHeight: 118, borderRadius: 16, border: "1px solid rgba(205,225,245,.78)", background: "#fff", padding: "12px 14px", color: "var(--text)", fontFamily: "var(--f-body)", fontSize: ".92rem", lineHeight: 1.6, outline: "none", resize: "none", boxShadow: "0 1px 0 rgba(255,255,255,.7) inset" },
  primary: dashboardShell.primaryButton,
  secondary: dashboardShell.secondaryButton,
  icon: { width: 40, height: 40, borderRadius: 12, border: "1px solid rgba(205,225,245,.76)", background: "#fff", color: "#2048a8", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  statCard: { ...dashboardShell.softPanel, padding: "14px 12px" },
  subtleCard: { ...dashboardShell.softPanel, padding: "10px 12px", borderRadius: 14 },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: 10,
    background: "rgba(36,86,191,.08)",
    color: "#2048a8",
    border: "1px solid rgba(36,86,191,.12)",
    fontFamily: "var(--f-ui)",
    fontSize: ".78rem",
    fontWeight: 700,
  },
  avatarAction: {
    position: "absolute",
    right: 4,
    bottom: 6,
    width: 34,
    height: 34,
    borderRadius: 12,
    border: "1px solid rgba(205,225,245,.76)",
    background: "#fff",
    color: "#2048a8",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 8px 22px rgba(14,30,60,.12)",
  },
};
